server:
  port: 8090

kafka:
  consumer:
    concurrency: 5
    group.id: boot-kafka-demo
    group.id.offset: boot-kafka-demo-offset
    servers: 118.31.54.101:9201,118.31.54.101:9202,118.31.54.101:9203
  producer:
    retries: 0
    servers: 118.31.54.101:9201,118.31.54.101:9202,118.31.54.101:9203

app:
  topic: test

logging:
  level:
    root: info
    org.springframework.web: INFO
    com.memorynotfound: DEBUG